// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client';
import type { GetApiProductsBalanceData, GetApiProductsBalanceErrors, GetApiProductsBalanceResponses, GetApiProductsListData, GetApiProductsListErrors, GetApiProductsListResponses, GetApiProductsSearchData, GetApiProductsSearchErrors, GetApiProductsSearchResponses, PostApiAuthLoginData, PostApiAuthLoginErrors, PostApiAuthLoginResponses, PostApiProductsBuyData, PostApiProductsBuyErrors, PostApiProductsBuyResponses, PostApiStatsReportData, PostApiStatsReportErrors, PostApiStatsReportResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login or register a new user.
 */
export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthLoginData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiAuthLoginResponses, PostApiAuthLoginErrors, ThrowOnError>({
        url: '/api/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get the current user's balance. Requires a valid auth token.
 */
export const getApiProductsBalance = <ThrowOnError extends boolean = false>(options?: Options<GetApiProductsBalanceData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiProductsBalanceResponses, GetApiProductsBalanceErrors, ThrowOnError>({
        url: '/api/products/balance',
        ...options
    });
};

/**
 * Buy a product. Requires a valid auth token.
 */
export const postApiProductsBuy = <ThrowOnError extends boolean = false>(options: Options<PostApiProductsBuyData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiProductsBuyResponses, PostApiProductsBuyErrors, ThrowOnError>({
        url: '/api/products/buy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Search for products. Requires a valid auth token.
 */
export const getApiProductsSearch = <ThrowOnError extends boolean = false>(options: Options<GetApiProductsSearchData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiProductsSearchResponses, GetApiProductsSearchErrors, ThrowOnError>({
        url: '/api/products/search',
        ...options
    });
};

/**
 * List all products. Requires a valid auth token.
 */
export const getApiProductsList = <ThrowOnError extends boolean = false>(options: Options<GetApiProductsListData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiProductsListResponses, GetApiProductsListErrors, ThrowOnError>({
        url: '/api/products/list',
        ...options
    });
};

/**
 * Report a user's activity. Requires a valid auth token.
 */
export const postApiStatsReport = <ThrowOnError extends boolean = false>(options: Options<PostApiStatsReportData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiStatsReportResponses, PostApiStatsReportErrors, ThrowOnError>({
        url: '/api/stats/report',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
