// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://hsekey.lxft.tech' | (string & {});
};

export type _Error = {
    message: string;
};

export type Token = {
    token: string;
};

export type Promocode = {
    code: string;
};

export type PostApiAuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Response for status 401
     */
    401: _Error;
    /**
     * Response for status 500
     */
    500: _Error;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * Response for status 200
     */
    200: Token;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiProductsBalanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/products/balance';
};

export type GetApiProductsBalanceErrors = {
    /**
     * Response for status 401
     */
    401: _Error;
    /**
     * Response for status 500
     */
    500: _Error;
};

export type GetApiProductsBalanceError = GetApiProductsBalanceErrors[keyof GetApiProductsBalanceErrors];

export type GetApiProductsBalanceResponses = {
    /**
     * Response for status 200
     */
    200: {
        balance: number;
    };
};

export type GetApiProductsBalanceResponse = GetApiProductsBalanceResponses[keyof GetApiProductsBalanceResponses];

export type PostApiProductsBuyData = {
    body: {
        productId: number;
    };
    path?: never;
    query?: never;
    url: '/api/products/buy';
};

export type PostApiProductsBuyErrors = {
    /**
     * Response for status 401
     */
    401: _Error;
    /**
     * Response for status 403
     */
    403: _Error;
    /**
     * Response for status 404
     */
    404: _Error;
    /**
     * Response for status 500
     */
    500: _Error;
};

export type PostApiProductsBuyError = PostApiProductsBuyErrors[keyof PostApiProductsBuyErrors];

export type PostApiProductsBuyResponses = {
    /**
     * Response for status 200
     */
    200: Promocode;
};

export type PostApiProductsBuyResponse = PostApiProductsBuyResponses[keyof PostApiProductsBuyResponses];

export type GetApiProductsSearchData = {
    body?: never;
    path?: never;
    query: {
        page: string | number;
        limit: string | number;
        query: string;
    };
    url: '/api/products/search';
};

export type GetApiProductsSearchErrors = {
    /**
     * Response for status 401
     */
    401: _Error;
    /**
     * Response for status 500
     */
    500: _Error;
};

export type GetApiProductsSearchError = GetApiProductsSearchErrors[keyof GetApiProductsSearchErrors];

export type GetApiProductsSearchResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: number;
        name: string;
        price: number;
        amount: number;
        imageUrl: string;
        createdAt: unknown | string | number;
    }>;
};

export type GetApiProductsSearchResponse = GetApiProductsSearchResponses[keyof GetApiProductsSearchResponses];

export type GetApiProductsListData = {
    body?: never;
    path?: never;
    query: {
        page: string | number;
        limit: string | number;
    };
    url: '/api/products/list';
};

export type GetApiProductsListErrors = {
    /**
     * Response for status 401
     */
    401: _Error;
    /**
     * Response for status 500
     */
    500: _Error;
};

export type GetApiProductsListError = GetApiProductsListErrors[keyof GetApiProductsListErrors];

export type GetApiProductsListResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: number;
        name: string;
        price: number;
        amount: number;
        imageUrl: string;
        createdAt: unknown | string | number;
    }>;
};

export type GetApiProductsListResponse = GetApiProductsListResponses[keyof GetApiProductsListResponses];

export type PostApiStatsReportData = {
    body: {
        count: number;
        activity: string;
    };
    path?: never;
    query?: never;
    url: '/api/stats/report';
};

export type PostApiStatsReportErrors = {
    /**
     * Response for status 401
     */
    401: _Error;
    /**
     * Response for status 500
     */
    500: _Error;
};

export type PostApiStatsReportError = PostApiStatsReportErrors[keyof PostApiStatsReportErrors];

export type PostApiStatsReportResponses = {
    /**
     * Response for status 200
     */
    200: {
        ok: boolean;
    };
};

export type PostApiStatsReportResponse = PostApiStatsReportResponses[keyof PostApiStatsReportResponses];
