volumes:
  postgres_data:

services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - "postgres_data:/var/lib/postgresql"
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped